import { Product } from '../types';

export const plantes: Product[] = [
  {
    id: 'plant1',
    title: 'Monstera Deliciosa',
    tag: 'Intérieur',
    description: 'Type: Plante tropicale d\'intérieur | Origine: Amérique Centrale | Exposition: Lumière indirecte | Arrosage: Hebdomadaire modéré | Conseils: Vaporiser les feuilles, nettoyer régulièrement',
    price: '120 DH / unité',
    image: '/images/plant1.jpg',
    category: 'plantes',
  },
  {
    id: 'plant2',
    title: 'Ficus Lyrata',
    tag: 'Intérieur',
    description: 'Type: Arbre d\'intérieur tropical | Origine: Afrique de l\'Ouest | Exposition: Lumière vive indirecte | Arrosage: Modéré toutes les 1-2 semaines | Conseils: Tourner le pot régulièrement',
    price: '180 DH / unité',
    image: '/images/plant2.jpg',
    category: 'plantes',
  },
  {
    id: 'plant3',
    title: 'Laurier Rose',
    tag: 'Extérieur',
    description: 'Type: Arbuste méditerranéen à fleurs | Origine: Bassin méditerranéen | Exposition: Plein soleil | Arrosage: Régulier modéré | Conseils: Tailler après floraison',
    price: '95 DH / unité',
    image: '/images/plant3.jpg',
    category: 'plantes',
  },
  {
    id: 'plant4',
    title: 'Palmier Nain',
    tag: 'Extérieur',
    description: 'Type: Palmier nain tropical | Origine: Méditerranée | Exposition: Plein soleil | Arrosage: Modéré à régulier | Conseils: Protéger du vent fort',
    price: '350 DH / unité',
    image: '/images/plant4.jpg',
    category: 'plantes',
  },
  {
    id: 'plant5',
    title: 'Hibiscus',
    tag: 'Floraison',
    description: 'Type: Arbuste à fleurs tropicales | Origine: Asie du Sud-Est | Exposition: Plein soleil | Arrosage: Régulier modéré | Conseils: Fertiliser pendant floraison',
    price: '95 DH / unité',
    image: '/images/plant5.jpg',
    category: 'plantes',
  },
  {
    id: 'plant6',
    title: 'Pothos Doré',
    tag: 'Intérieur',
    description: 'Type: Plante grimpante tropicale | Origine: Polynésie | Exposition: Ombre à lumière indirecte | Arrosage: Léger hebdomadaire | Conseils: Nettoyer les feuilles',
    price: '55 DH / unité',
    image: '/images/plant6.jpg',
    category: 'plantes',
  },
  {
    id: 'plant7',
    title: 'Lotus Sacré',
    tag: 'Aquatique',
    description: 'Type: Plante aquatique sacrée | Origine: Asie | Exposition: Plein soleil | Arrosage: Eau stagnante | Conseils: Planter dans vase profond',
    price: '180 DH / unité',
    image: '/images/plant7.jpg',
    category: 'plantes',
  },
  {
    id: 'plant8',
    title: 'Bambou Sacré',
    tag: 'Extérieur',
    description: 'Type: Bambou à croissance rapide | Origine: Asie | Exposition: Plein soleil à mi-ombre | Arrosage: Régulier abondant | Conseils: Contrôler les racines',
    price: '130 DH / pot',
    image: '/images/plant8.jpg',
    category: 'plantes',
  },
  {
    id: 'plant9',
    title: 'Rosier Grimpant',
    tag: 'Floraison',
    description: 'Type: Rosier grimpant à fleurs | Origine: Europe | Exposition: Plein soleil | Arrosage: Régulier modéré | Conseils: Tailler en fin d\'hiver',
    price: '115 DH / unité',
    image: '/images/plant9.jpg',
    category: 'plantes',
  },
];

export const pots: Product[] = [
  {
    id: 'pot1',
    title: 'Pot Artisanal',
    tag: 'Accessoires',
    description: 'Dimensions: H25cm x D25cm | Matériau: Terre cuite traditionnelle | Style: Artisanal marocain | Usage: Plantes d\'intérieur et extérieur',
    price: '75 DH / unité',
    image: '/images/pot1.jpg',
    category: 'pots',
  },
  {
    id: 'pot2',
    title: 'Jardinière Moderne',
    tag: 'Accessoires',
    description: 'Dimensions: L40cm x l20cm x H15cm | Matériau: Céramique émaillée | Style: Design moderne | Usage: Plantes d\'intérieur et balcons',
    price: '140 DH / unité',
    image: '/images/pot2.jpg',
    category: 'pots',
  },
  {
    id: 'pot3',
    title: 'Pot Macramé',
    tag: 'Accessoires',
    description: 'Dimensions: H60cm avec pot D15cm | Matériau: Corde de coton naturelle | Style: Bohème chic | Usage: Plantes retombantes',
    price: '60 DH / unité',
    image: '/images/pot3.jpg',
    category: 'pots',
  },
  {
    id: 'pot4',
    title: 'Cube Béton',
    tag: 'Accessoires',
    description: 'Dimensions: 20cm x 20cm x 20cm | Matériau: Béton léger | Style: Design industriel | Usage: Plantes modernes et succulentes',
    price: '95 DH / unité',
    image: '/images/pot4.jpg',
    category: 'pots',
  },
  {
    id: 'pot5',
    title: 'Bac en Bois',
    tag: 'Accessoires',
    description: 'Dimensions: L60cm x l30cm x H25cm | Matériau: Bois traité | Style: Rustique naturel | Usage: Terrasses et balcons',
    price: '220 DH / unité',
    image: '/images/pot5.jpg',
    category: 'pots',
  },
  {
    id: 'pot6',
    title: 'Pot Zellige',
    tag: 'Céramique émaillée',
    description: 'Dimensions: H30cm x D25cm | Matériau: Céramique émaillée | Style: Zellige marocain | Usage: Plantes décoratives',
    price: '185 DH / unité',
    image: '/images/pot6.jpg',
    category: 'pots',
  },
  {
    id: 'pot7',
    title: 'Pot Éco',
    tag: 'Recyclé',
    description: 'Dimensions: H20cm x D18cm | Matériau: Plastique recyclé | Style: Éco-responsable | Usage: Plantes d\'intérieur',
    price: '45 DH / unité',
    image: '/images/pot7.jpg',
    category: 'pots',
  },
  {
    id: 'pot8',
    title: 'Vasque Décorative',
    tag: 'Prestige',
    description: 'Dimensions: L80cm x l40cm x H15cm | Matériau: Pierre naturelle | Style: Prestige | Usage: Entrées et espaces extérieurs',
    price: '480 DH / unité',
    image: '/images/pot8.jpg',
    category: 'pots',
  },
  {
    id: 'pot9',
    title: 'Cache-pot Zinc',
    tag: 'Métal',
    description: 'Dimensions: H25cm x D22cm | Matériau: Zinc vieilli | Style: Campagne chic | Usage: Cache-pot décoratif',
    price: '110 DH / unité',
    image: '/images/pot9.jpg',
    category: 'pots',
  },
];

export const soins: Product[] = [
  {
    id: 'med1',
    title: 'Engrais Bio',
    tag: 'Entretien',
    description: 'Type: Engrais organique liquide | Durée: 6 mois d\'utilisation | Mode d\'emploi: Diluer 1L dans 10L d\'eau | Moment: Printemps et été | Composition: NPK 5-3-7',
    price: 'à partir de 35 DH',
    image: '/images/med1.jpg',
    category: 'soins',
  },
  {
    id: 'med2',
    title: 'Traitements Anti-parasites',
    tag: 'Entretien',
    description: 'Type: Traitement bio contre nuisibles | Durée: 4 mois d\'utilisation | Mode d\'emploi: Pulvériser sur feuilles | Moment: Au premier signe d\'infestation | Composition: Huiles essentielles',
    price: 'à partir de 50 DH',
    image: '/images/med2.jpg',
    category: 'soins',
  },
  {
    id: 'med3',
    title: 'Substrats Spéciaux',
    tag: 'Entretien',
    description: 'Type: Terreau spécialisé | Durée: 12 mois d\'utilisation | Mode d\'emploi: Remplacer annuellement | Moment: Au repiquage | Composition: Tourbe, perlite, écorce',
    price: 'à partir de 40 DH',
    image: '/images/med3.jpg',
    category: 'soins',
  },
];

export const oiseaux: Product[] = [
  {
    id: 'bird1',
    title: 'Perroquet Vert',
    tag: 'Oiseaux',
    description: 'Type: Perroquet amazone à bec fort | Aliment: Mélange de graines exotiques | Ingrédients: Tournesol, millet, maïs | Espèces: Perroquets, perruches, cacatoès',
    price: '1 200 DH',
    image: '/images/bird1.jpg',
    category: 'oiseaux',
  },
  {
    id: 'bird2',
    title: 'Canari Mélodieux',
    tag: 'Oiseaux',
    description: 'Type: Canari jaune chanteur | Aliment: Mélange de graines fines | Ingrédients: Alpiste, navette, chènevis | Espèces: Canaris, serins, verdiers',
    price: '350 DH',
    image: '/images/bird2.jpg',
    category: 'oiseaux',
  },
];

export const bouquets: Product[] = [
  {
    id: 'fleur1',
    title: 'Bouquet Romantique',
    tag: 'Mariage',
    description: 'Fleurs: Roses roses, pivoines blanches | Couleurs: Rose, blanc, vert pastel | Nombre: 25 fleurs | Occasion: Mariage, fiançailles',
    price: '380 DH',
    image: '/images/fleur1.jpg',
    category: 'bouquets',
  },
  {
    id: 'fleur2',
    title: 'Bouquet Soleil',
    tag: 'Cadeau',
    description: 'Fleurs: Tournesols jaunes, marguerites blanches | Couleurs: Jaune, blanc, vert | Nombre: 20 fleurs | Occasion: Anniversaire, remerciements',
    price: '180 DH',
    image: '/images/fleur2.jpg',
    category: 'bouquets',
  },
  {
    id: 'fleur3',
    title: 'Composition Verte',
    tag: 'Moderne',
    description: 'Fleurs: Feuillages tropicaux, orchidées blanches, monstera | Couleurs: Vert, blanc, émeraude | Nombre: 18 éléments | Occasion: Décoration moderne, bureau',
    price: '250 DH',
    image: '/images/fleur3.jpg',
    category: 'bouquets',
  },
  {
    id: 'fleur4',
    title: 'Roses Rouges',
    tag: 'Amour',
    description: 'Fleurs: 12 roses rouges premium | Couleurs: Rouge passion | Nombre: 12 fleurs | Occasion: Déclaration d\'amour, Saint-Valentin',
    price: '220 DH',
    image: '/images/fleur4.jpg',
    category: 'bouquets',
  },
  {
    id: 'fleur5',
    title: 'Bouquet Sakura',
    tag: 'Printemps',
    description: 'Fleurs: Cerisiers, lilas, fleurs de pommier | Couleurs: Rose, blanc, violet | Nombre: 18 fleurs | Occasion: Printemps, renouveau',
    price: '290 DH',
    image: '/images/fleur5.jpg',
    category: 'bouquets',
  },
  {
    id: 'fleur6',
    title: 'Bouquet Champêtre',
    tag: 'Nature',
    description: 'Fleurs: Coquelicots, bleuets, lavande, marguerites | Couleurs: Jaune, bleu, violet, blanc | Nombre: 22 fleurs | Occasion: Jardin, décoration naturelle',
    price: '160 DH',
    image: '/images/fleur6.jpg',
    category: 'bouquets',
  },
  {
    id: 'fleur7',
    title: 'Tropical',
    tag: 'Luxe',
    description: 'Fleurs: Strelitzias, anthuriums, feuilles de monstera | Couleurs: Orange, rouge, vert | Nombre: 15 éléments | Occasion: Événements spéciaux, luxe',
    price: '420 DH',
    image: '/images/fleur7.jpg',
    category: 'bouquets',
  },
  {
    id: 'fleur8',
    title: 'Bouquet Blanc Pur',
    tag: 'Élégance',
    description: 'Fleurs: Lys blancs, orchidées phalaenopsis, roses blanches | Couleurs: Blanc pur, touches de vert | Nombre: 20 fleurs | Occasion: Mariages, baptêmes',
    price: '550 DH',
    image: '/images/fleur8.jpg',
    category: 'bouquets',
  },
  {
    id: 'fleur9',
    title: 'Coucher de Soleil',
    tag: 'Automne',
    description: 'Fleurs: Tulipes orangées, dahlias, chrysanthèmes, roses | Couleurs: Orange, rouge, jaune | Nombre: 18 fleurs | Occasion: Automne, Thanksgiving',
    price: '200 DH',
    image: '/images/fleur9.jpg',
    category: 'bouquets',
  },
  {
    id: 'fleur10',
    title: 'Composition Zen',
    tag: 'Zen',
    description: 'Fleurs: Bambou, mousse, fleurs blanches, orchidées | Couleurs: Vert, blanc, émeraude | Nombre: 12 éléments | Occasion: Méditation, spa, bureau',
    price: '310 DH',
    image: '/images/fleur10.jpg',
    category: 'bouquets',
  },
  {
    id: 'fleur11',
    title: 'Bouquet Violet',
    tag: 'Luxe',
    description: 'Fleurs: Jacinthes, lilas, iris violets, delphiniums | Couleurs: Violet, lavande, blanc | Nombre: 16 fleurs | Occasion: Événements élégants, luxe',
    price: '340 DH',
    image: '/images/fleur11.jpg',
    category: 'bouquets',
  },
  {
    id: 'fleur12',
    title: 'Bouquet Fête',
    tag: 'Célébration',
    description: 'Fleurs: Gerberas, asters, roses, marguerites | Couleurs: Multicolore vif | Nombre: 25 fleurs | Occasion: Anniversaire, fêtes, célébrations',
    price: '195 DH',
    image: '/images/fleur12.jpg',
    category: 'bouquets',
  },
  {
    id: 'fleur13',
    title: 'Décoration Bureau',
    tag: 'Professionnel',
    description: 'Fleurs: Monstera, ficus, philodendron | Couleurs: Vert, blanc, touches de couleur | Nombre: 8 plantes | Occasion: Bureaux, hôtels, réceptions',
    price: '450 DH',
    image: '/images/fleur13.jpg',
    category: 'bouquets',
  },
  {
    id: 'fleur14',
    title: 'Cœur Fleuri',
    tag: 'Amour',
    description: 'Fleurs: 15 roses rouges, 10 œillets rouges | Couleurs: Rouge passion | Nombre: 25 fleurs | Occasion: Saint-Valentin, déclaration d\'amour',
    price: '490 DH',
    image: '/images/fleur14.jpg',
    category: 'bouquets',
  },
  {
    id: 'fleur15',
    title: 'Création Personnalisée',
    tag: 'Sur mesure',
    description: 'Fleurs: Selon votre choix | Couleurs: Personnalisées | Nombre: Variable | Occasion: Événements spéciaux, sur mesure',
    price: 'Sur devis',
    image: '/images/fleur15.jpg',
    category: 'bouquets',
  },
  {
    id: 'fleur16',
    title: 'Bouquet Méditerranéen',
    tag: 'Été',
    description: 'Fleurs: Lavande, santoline, immortelles, olivier | Couleurs: Violet, blanc, jaune | Nombre: 20 éléments | Occasion: Été, décoration provençale',
    price: '175 DH',
    image: '/images/fleur16.jpg',
    category: 'bouquets',
  },
  {
    id: 'fleur17',
    title: 'Bouquet Naissance',
    tag: 'Naissance',
    description: 'Fleurs: Roses pastel, gypsophiles, eucalyptus | Couleurs: Rose pâle, blanc, vert tendre | Nombre: 18 fleurs | Occasion: Naissance, baptême',
    price: '260 DH',
    image: '/images/fleur17.jpg',
    category: 'bouquets',
  },
  {
    id: 'fleur18',
    title: 'Bouquet Éternel',
    tag: 'Durable',
    description: 'Fleurs: Hélichrysum, statice, lavande, roses séchées | Couleurs: Naturels, dorés, blancs | Nombre: 15 éléments | Occasion: Décoration durable, cadeau souvenir',
    price: '285 DH',
    image: '/images/fleur18.jpg',
    category: 'bouquets',
  },
  {
    id: 'fleur19',
    title: 'One-Stem',
    tag: 'Minimaliste',
    description: 'L\'art du minimalisme floral, une seule fleur exceptionnelle sublimée dans un vase.',
    price: '95 DH',
    image: '/images/fleur19.jpg',
    category: 'bouquets',
  },
  {
    id: 'fleur20',
    title: 'Corbeille Luxe',
    tag: 'Affaires',
    description: 'Grande corbeille fleurie avec ruban et carte personnalisée, idéale en affaires.',
    price: '650 DH',
    image: '/images/fleur20.jpg',
    category: 'bouquets',
  },
  {
    id: 'fleur21',
    title: 'Bouquet Hivernal',
    tag: 'Hiver',
    description: 'Houx, baies rouges et branches enneigées, magie de l\'hiver dans vos mains.',
    price: '230 DH',
    image: '/images/fleur21.jpg',
    category: 'bouquets',
  },
  {
    id: 'fleur22',
    title: 'Bouquet Passion',
    tag: 'Audacieux',
    description: 'Protéas, roses noires et leucadendrons pour une composition audacieuse et inoubliable.',
    price: '580 DH',
    image: '/images/fleur22.jpg',
    category: 'bouquets',
  },
  {
    id: 'fleur23',
    title: 'Bouquet Aromatique',
    tag: 'Parfumé',
    description: 'Romarin, thym, lavande et basilic pourpre, bouquet décoratif et parfumé.',
    price: '130 DH',
    image: '/images/fleur23.jpg',
    category: 'bouquets',
  },
  {
    id: 'fleur24',
    title: 'Bouquet Maman',
    tag: 'Fête des mères',
    description: 'Pivoines, roses et freesias, la composition idéale pour honorer votre maman.',
    price: '320 DH',
    image: '/images/fleur24.jpg',
    category: 'bouquets',
  },
];

export const jardinImages = [
  '/images/jardin1.jpg',
  '/images/jardin2.jpg',
  '/images/jardin3.jpg',
  '/images/jardin4.jpg',
  '/images/jardin5.jpg',
  '/images/jardin6.jpg',
  '/images/jardin7.jpg',
  '/images/jardin8.jpg',
  '/images/jardin9.jpg',
  '/images/jardin10.jpg',
  '/images/jardin11.jpg',
  '/images/jardin12.jpg',
  '/images/jardin13.jpg',
  '/images/jardin14.jpg',
  '/images/jardin15.jpg',
  '/images/jardin16.jpg',
  '/images/jardin17.jpg',
  '/images/jardin18.jpg',
  '/images/jardin19.jpg',
  '/images/jardin20.jpg',
  '/images/jardin21.jpg',
  '/images/jardin22.jpg',
  '/images/jardin23.jpg',
];
